export type FormBackendErrorCode = 'INTERNAL_SERVER_ERROR' |
  'MISSING_LOOKUP_TABLES' |
  'MISSING_LOOKUP_COLUMNS' |
  'FORM_ID_MISSING' |
  'ITEM_ID_MISSING' |
  'FORM_CONFIG_NOT_FOUND' |
  'INVALID_FILE' |
  'CONFIG_KEY_IS_EMPTY' |
  'DB_JOIN_ITEMS_NOT_FOUND_FOR_CONFIG_KEYS' |
  'JOIN_TABLE_DATA_CREATION_FAILED' |
  'JOIN_TABLE_DATA_DELETION_FAILED' |
  'ITEM_CREATION_FAILED' |
  'LOOKUP_TABLE_PROPERTY_NOT_FOUND' |
  'JOIN_TABLE_NOT_FOUND' |
  'JOIN_TABLE_PROP_NOT_FOUND' |
  'JOIN_TABLE_RELATIONSHIP_NOT_SUPPORTED' |
  'INVALID_ORDER' |
  'INVALID_ORDER_BY' |
  'INVALID_PAGE' |
  'INVALID_FILTER';
