FROM mcr.microsoft.com/playwright:v1.48.2-focal@sha256:c37bcb50b237e975f3fe80013ab1b3958946db1b24aba39b52be8b3123b8a3df

WORKDIR /form-backend
COPY app/package.json app/package-lock.json ./

RUN npm install -D @playwright/test

RUN npm install dotenv@v16.3.1
RUN npm ci
RUN npx playwright install --with-deps

COPY ./app/playwright.config.ts ./
COPY ./app/global-setup.js ./
COPY ./app/e2e-tests ./e2e-tests
