services:

  nginx:
    image: nginx:1.27.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - keycloak
      - form-backend

  postgres:
    image: postgis/postgis:16-3.4-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres/init_data:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data

  postgrest:
    image: postgrest/postgrest:v12.2.2
    environment:
      PGRST_DB_URI: ${PGRST_DB_URI}
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_DB_SCHEMAS: ${PGRST_DB_SCHEMAS}
      PGRST_DB_ANON_ROLE: ${PGRST_DB_ANON_ROLE}
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
      PGRST_JWT_ROLE_CLAIM_KEY: ${PGRST_JWT_ROLE_CLAIM_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
    depends_on:
      - postgres

  form-backend:
    build:
      context: ../
    environment:
      POSTGREST_URL: "http://postgrest:3000"
      POSTGREST_SCHEMA: ${PGRST_DB_SCHEMAS}
      POSTGREST_DEFAULT_SCHEMA: ${POSTGREST_DEFAULT_SCHEMA}
      POSTGREST_JWT_CLIENT_ID: ${PGRST_KEYCLOAK_CLIENT_ID}
      POSTGREST_KEYCLOAK_CLIENT_SECRET: ${PGRST_KEYCLOAK_CLIENT_SECRET}
      FORM_CONFIGS_DIR: "form_configs"
      FILE_UPLOAD_DIR: ${FB_FILE_UPLOAD_DIR}
      SIZE_LIMIT: ${FB_SIZE_LIMIT}
      KC_REALM: ${KEYCLOAK_REALM}
      KC_AUTH_SERVER_URL: ${FB_KC_AUTH_SERVER_URL}
      KC_CLIENT_APP_ID: ${FB_KC_CLIENT_APP_ID}
      KC_PUBLIC_KEY: ${KEYCLOAK_PUBLIC_KEY}
    volumes:
      - ./form-backend/form_configs:/form-backend/form_configs
      - ./form-backend/uploads:/form-backend/uploads
    depends_on:
      - postgrest

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: postgres-keycloak
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HOSTNAME: ${KEYCLOAK_HOST}
      KC_HOSTNAME_PORT: ${KEYCLOAK_PORT}
      KC_HOSTNAME_PATH: /auth
      KC_HTTP_RELATIVE_PATH: /auth
    depends_on:
      - postgres-keycloak
    command: ["start", "--proxy", "edge", "--health-enabled=true"]
    healthcheck:
      test: cat /proc/net/tcp6 | grep '00000000000000000000000000000000:1F90 00000000000000000000000000000000:0000 0A' || exit 1
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s

  postgres-keycloak:
    image: postgis/postgis:16-3.4-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-keycloak/init_data:/docker-entrypoint-initdb.d
      - ./postgres-keycloak/data:/var/lib/postgresql/data
