name: Test successful build of form-backend on pull request

on: pull_request

jobs:
  build_and_test_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources 🔰
        uses: actions/checkout@v4

      - name: Setup Node.js 🧮
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache Node.js modules 💾
        uses: actions/cache@v4
        with:
          path: ~/app/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies ⏬
        working-directory: ./app
        run: npm ci

      - name: Run typecheck, lint and tests 🧪
        working-directory: ./app
        run: npm run check && npm run test

      - name: Build artifacts 🏗️
        working-directory: ./app
        run: npm run build
  build_and_test_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources 🔰
        uses: actions/checkout@v4

      - name: Setup Node.js 🧮
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache Node.js modules 💾
        uses: actions/cache@v4
        with:
          path: ~/backend/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies ⏬
        working-directory: ./backend
        run: npm ci

      - name: Run typecheck, lint and tests 🧪
        working-directory: ./backend
        run: npm run lint && npm run test

      - name: Build artifacts 🏗️
        working-directory: ./backend
        run: npm run build
